### PR TITLE
update Travis config

### PR DESCRIPTION
**Pull request by ericcf**
* use Docker
* test with Ruby 2.3.0

### CODE REVIEW

**Comment by eschlange** [comment]
@ericcf Changes look good, should I merge this and create a story to deal with the Hakiri complaints?

**Comment by ericcf** [comment]
@eschlange nah, I'll just add a commit with the patches. I don't know how to run the acceptance test suite, so we'll have to wait until next week to deploy to production anyway.

**Comment by ericcf** [comment]
Decision to leave paperclip unpatched until further development takes place due to breaking changes.

**Comment by ericcf** [comment]
@eschlange mind merging this (and ignoring the paperclip warning from Hakiri for now)?

**Pull request merged**
